<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>利用Civil 3D API更改曲面的样式 « NotBeCN</title>
  <meta name="description" content="                      如果你需要更改曲面的样式，比如更改等高线的颜色等等，在Civil 3D中，你可以通过在toolspace中选中曲面，然后点右键选择“Edit surface style…”然后切换到“Display” tab 来更改，:          下面的通过代码的方式使用API...">

  <link rel="stylesheet" href="/css/main.css">
  <link rel="canonical" href="https://notbe.cn/2016/09/06/weixin_34248023_90127740.html">
  <link rel="alternate" type="application/rss+xml" title="NotBeCN" href="https://notbe.cn/feed.xml" />
</head>


  <body>

    <div class="header-placeholder"></div>
<header class="header">
  <div class="wrapper">
    <div id="sidebar-toggle">TOC</div>
    <a class="site-title" href="/">NotBeCN</a>
    <nav class="site-nav">
      
        
        <a class="page-link" href="/about/" target="_blank">关于</a>
      
        
        <a class="page-link" href="https://uzshare.com" target="_blank">社区</a>
      
        
        <a class="page-link" href="/donate/" target="_blank">Donate</a>
      
        
        <a class="page-link" href="/games/shejiyazi/" target="_blank">射个鸭子</a>
      
    </nav>
  </div>
</header>


    <div class="page-content">
      <div class="wrapper">
        <div class="col-main">
          <div class="post">

  <header class="post-header">
    <h1 class="post-title">利用Civil 3D API更改曲面的样式</h1>
    <p class="post-meta">Sep 6, 2016</p>
  </header>

  <article class="post-content">
    <div id="article_content" class="article_content clearfix csdn-tracking-statistics" data-pid="blog" data-mod="popu_307" data-dsm="post"> 
 <link rel="stylesheet" href="https://csdnimg.cn/release/phoenix/template/css/ck_htmledit_views-f57960eb32.css"> 
 <link rel="stylesheet" href="https://csdnimg.cn/release/phoenix/template/css/ck_htmledit_views-f57960eb32.css"> 
 <div class="htmledit_views" id="content_views"> 
  <div class="content-detail markdown-body"> 
   <h1 style="font-size:14.7px;color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;"><br></h1> 
   <div class="blogpost-body" style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;"> 
    <p style="line-height:1.5;">如果你需要更改曲面的样式，比如更改等高线的颜色等等，在Civil 3D中，你可以通过在toolspace中选中曲面，然后点右键选择“Edit surface style…”然后切换到“Display” tab 来更改，:</p> 
    <p style="line-height:1.5;"><a href="https://images0.cnblogs.com/blog/30437/201412/291959349976178.png" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><img title="image" src="https://images0.cnblogs.com/blog/30437/201412/291959365596433.png" alt="image" width="452" height="362" style="border:0px;"></a></p> 
    <p style="line-height:1.5;">下面的通过代码的方式使用API来实现同样的效果:</p> 
    <pre>[<span style="line-height:1.5;color:rgb(43,145,175);">CommandMethod</span>(<span style="line-height:1.5;color:rgb(163,21,21);">"MyGroup"</span>, <span style="line-height:1.5;color:rgb(163,21,21);">"SurfaceStyleExample"</span>, <br>
&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(163,21,21);">"SurfaceStyleExample"</span>, <span style="line-height:1.5;color:rgb(43,145,175);">CommandFlags</span>.Modal)]<br><span style="line-height:1.5;color:#0000FF;">public</span>&nbsp;<span style="line-height:1.5;color:#0000FF;">void</span> MyCommand() <span style="line-height:1.5;color:#008000;">// This method can have any name</span><br>
{<br>
&nbsp;<br>
&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(43,145,175);">Document</span> doc = <span style="line-height:1.5;color:rgb(43,145,175);">Application</span>.DocumentManager.MdiActiveDocument;<br>
&nbsp;&nbsp;&nbsp; <br>
&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#0000FF;">if</span> (doc != <span style="line-height:1.5;color:#0000FF;">null</span>)<br>
&nbsp;&nbsp;&nbsp; {<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(43,145,175);">Editor</span> ed = <span style="line-height:1.5;color:rgb(43,145,175);">Application</span>.DocumentManager<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .MdiActiveDocument.Editor;<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">// select a tin surface</span><br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(43,145,175);">PromptEntityOptions</span> peo = <span style="line-height:1.5;color:#0000FF;">new</span>&nbsp;<span style="line-height:1.5;color:rgb(43,145,175);">PromptEntityOptions</span>(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(163,21,21);">"\nSelect a tin surface: "</span>);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; peo.SetRejectMessage(<span style="line-height:1.5;color:rgb(163,21,21);">"\nOnly Tin surface is accepted"</span>);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; peo.AddAllowedClass(<span style="line-height:1.5;color:#0000FF;">typeof</span>(<span style="line-height:1.5;color:rgb(43,145,175);">TinSurface</span>), <span style="line-height:1.5;color:#0000FF;">true</span>);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(43,145,175);">PromptEntityResult</span> per = ed.GetEntity(peo);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#0000FF;">if</span> (per.Status != <span style="line-height:1.5;color:rgb(43,145,175);">PromptStatus</span>.OK) <span style="line-height:1.5;color:#0000FF;">return</span>;<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(43,145,175);">CivilDocument</span> civilDoc = <span style="line-height:1.5;color:rgb(43,145,175);">CivilApplication</span>.ActiveDocument;<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#0000FF;">using</span> (<span style="line-height:1.5;color:rgb(43,145,175);">Transaction</span> trans = doc.TransactionManager<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .StartTransaction())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(43,145,175);">TinSurface</span> surface = trans.GetObject(per.ObjectId, <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(43,145,175);">OpenMode</span>.ForRead) <span style="line-height:1.5;color:#0000FF;">as</span>&nbsp;<span style="line-height:1.5;color:rgb(43,145,175);">TinSurface</span>;<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">//exclude invalid points， 附赠功能，排除异常点</span><br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surface.BuildOptions.ExecludeMaximumElevation = <span style="line-height:1.5;color:#0000FF;">true</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surface.BuildOptions.MaximumElevation = 5000;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surface.BuildOptions.ExecludeMinimumElevation = <span style="line-height:1.5;color:#0000FF;">true</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surface.BuildOptions.MinimumElevation = 200;<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">//set the Maximum Triangle Length，设置三角形最大边长</span><br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surface.BuildOptions.MaximumTriangleLength = 200;<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">//change the style， 下面开始更改样式了</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(43,145,175);">ObjectId</span> styleId;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#0000FF;">if</span> (civilDoc.Styles.SurfaceStyles.Contains(<span style="line-height:1.5;color:rgb(163,21,21);">"Standard"</span>))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; styleId = civilDoc.Styles.SurfaceStyles[<span style="line-height:1.5;color:rgb(163,21,21);">"Standard"</span>];<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#0000FF;">else</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">// create a new style called 'example style':</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; styleId = civilDoc.Styles.SurfaceStyles<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .Add(<span style="line-height:1.5;color:rgb(163,21,21);">"example style"</span>);<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">// modify the style</span><br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(43,145,175);">SurfaceStyle</span> surfaceStyle = styleId.GetObject(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(43,145,175);">OpenMode</span>.ForWrite) <span style="line-height:1.5;color:#0000FF;">as</span>&nbsp;<span style="line-height:1.5;color:rgb(43,145,175);">SurfaceStyle</span>;<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">//countours smoothing </span><br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.ContourStyle.SmoothContours = <span style="line-height:1.5;color:#0000FF;">true</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.ContourStyle.SmoothingType <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; = <span style="line-height:1.5;color:rgb(43,145,175);">ContourSmoothingType</span>.AddVertices;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.ContourStyle.SmoothingFactor = 10;<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.ContourStyle.MajorContourColorScheme <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; = <span style="line-height:1.5;color:rgb(43,145,175);">ColorSchemeType</span>.Rainbow;<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">//Major contour, red</span><br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.GetDisplayStylePlan(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(43,145,175);">SurfaceDisplayStyleType</span>.MajorContour).Color <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; = Autodesk.AutoCAD.Colors.<span style="line-height:1.5;color:rgb(43,145,175);">Color</span>.FromRgb(255, 0, 0);<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">//Major contour, layer 0</span><br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.GetDisplayStylePlan(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(43,145,175);">SurfaceDisplayStyleType</span>.MajorContour).Layer = <span style="line-height:1.5;color:rgb(163,21,21);">"0"</span>;<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">//Mainor contour, gree</span><br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.GetDisplayStylePlan(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(43,145,175);">SurfaceDisplayStyleType</span>.MinorContour).Color <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; = Autodesk.AutoCAD.Colors.<span style="line-height:1.5;color:rgb(43,145,175);">Color</span>.FromRgb(0, 255, 0);<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">//Mainor contour, layer 0， 如果你要放在其他图层，要确保该图层存在</span><br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.GetDisplayStylePlan(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:rgb(43,145,175);">SurfaceDisplayStyleType</span>.MajorContour).Layer = <span style="line-height:1.5;color:rgb(163,21,21);">"0"</span>;<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">// display major contours:</span><br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.GetDisplayStylePlan(<span style="line-height:1.5;color:rgb(43,145,175);">SurfaceDisplayStyleType</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .MajorContour).Visible = <span style="line-height:1.5;color:#0000FF;">true</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.GetDisplayStylePlan(<span style="line-height:1.5;color:rgb(43,145,175);">SurfaceDisplayStyleType</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .MinorContour).Visible = <span style="line-height:1.5;color:#0000FF;">true</span>;<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">// turn off display of other items:</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.GetDisplayStylePlan(<span style="line-height:1.5;color:rgb(43,145,175);">SurfaceDisplayStyleType</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .UserContours).Visible = <span style="line-height:1.5;color:#0000FF;">false</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.GetDisplayStylePlan(<span style="line-height:1.5;color:rgb(43,145,175);">SurfaceDisplayStyleType</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .Directions).Visible = <span style="line-height:1.5;color:#0000FF;">false</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.GetDisplayStylePlan(<span style="line-height:1.5;color:rgb(43,145,175);">SurfaceDisplayStyleType</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .Elevations).Visible = <span style="line-height:1.5;color:#0000FF;">false</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.GetDisplayStylePlan(<span style="line-height:1.5;color:rgb(43,145,175);">SurfaceDisplayStyleType</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .Slopes).Visible = <span style="line-height:1.5;color:#0000FF;">false</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.GetDisplayStylePlan(<span style="line-height:1.5;color:rgb(43,145,175);">SurfaceDisplayStyleType</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .SlopeArrows).Visible = <span style="line-height:1.5;color:#0000FF;">false</span>;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surfaceStyle.GetDisplayStylePlan(<span style="line-height:1.5;color:rgb(43,145,175);">SurfaceDisplayStyleType</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .Watersheds).Visible = <span style="line-height:1.5;color:#0000FF;">false</span>;<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">//TODO: do the same for all model display settings as well</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">// </span><br><br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">// assign the style to the first surface in the document:</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surface.StyleId = styleId;<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">// commit the transaction</span><br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; trans.Commit();<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="line-height:1.5;color:#008000;">//rebuild the surface </span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; surface.Rebuild();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br><br>
&nbsp;&nbsp;&nbsp; }<br><br><br><br>
}</pre> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;">改之前的样子:</p> 
    <p style="line-height:1.5;"><a href="https://images0.cnblogs.com/blog/30437/201412/291959390132018.png" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><img title="image" src="https://images0.cnblogs.com/blog/30437/201412/291959405137759.png" alt="image" width="396" height="320" style="border:0px;"></a></p> 
    <p style="line-height:1.5;">运行之后，等高线的颜色已经改变了.</p> 
    <p style="line-height:1.5;"><a href="https://images0.cnblogs.com/blog/30437/201412/291959428885600.png" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><img title="image" src="https://images0.cnblogs.com/blog/30437/201412/291959445442529.png" alt="image" width="404" height="332" style="border:0px;"></a></p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;">Hope this helps.</p> 
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    作者：
    <a href="http://junqilian.cnblogs.com/" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;">峻祁连</a>
    <br> 邮箱：junqilian@163.com&nbsp;
    <br> 出处：
    <a href="http://junqilian.cnblogs.com/" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;">http://junqilian.cnblogs.com</a>&nbsp;
    <br> 转载请保留此信息。
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    <br>
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    <br>
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    <br>
   </div> 
   <div> 
    <h1> <font color="#4b4b4b"><span style="font-size:18px;">本文转自峻祁连. Moving to Cloud/Mobile博客园博客，原文链接：http://www.cnblogs.com/junqilian/p/4192313.html</span></font>，如需转载请自行联系原作者</h1> 
   </div> 
  </div> 
 </div> 
</div>
  </article>
  
  




</div>

        </div>
        <div class="col-second">
          <div class="col-box col-box-author">
  <img class="avatar" src="https://uzstatic-360cdn.belost.xyz/theme/default/images/logo.png" alt="柚子社区">
  <div class="col-box-title name">NotBeCN</div>
  <!-- <p>最新资讯</p> -->
  <p class="contact">
    
    <a href="mailto:fandyvon@163.com" target="_blank">邮箱</a>
    
    <a href="https://uzshare.com" target="_blank">柚子社区</a>
    
    <a href="https://uzzz.org" target="_blank">找组织</a>
    
  </p>
</div>

<div class="col-box">
  <div class="col-box-title">最新</div>
  <ul class="post-list">
    
      <li><a class="post-link" href="/2019/05/14/zxh1220_90138586.html">[原创软件] [软件发布] 定时备份文件发送邮箱，不再怕数据丢失了</a></li>
    
      <li><a class="post-link" href="/2019/05/14/weixin_45037290_90140056.html">Get智能写作满月记 ——产品篇</a></li>
    
      <li><a class="post-link" href="/2019/05/14/nulio__90138386.html">《深度探索C++对象模型》..............</a></li>
    
      <li><a class="post-link" href="/2019/05/13/qq_41248707_90140031.html">mysql 多表联查之连接查询</a></li>
    
      <li><a class="post-link" href="/2019/05/13/qq_21122683_90125902.html">golang基础(二)</a></li>
    
      <li><a class="post-link" href="/2019/05/13/1557726108256.html">今日份的PTA刷题</a></li>
    
      <li><a class="post-link" href="/2019/05/12/zzzfffei_90137366.html">Android之折线图</a></li>
    
      <li><a class="post-link" href="/2019/05/12/zzzfffei_90136638.html">Android之实现选中时改变样式</a></li>
    
  </ul>
</div>

<div class="col-box post-toc hide">
  <div class="col-box-title">目录</div>
</div>

<div class="col-box">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- right_sidebar -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8889449066804352"
       data-ad-slot="2081363239"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>


        </div>
      </div>
    </div>

    <footer class="footer">
<div class="wrapper">
&copy; 2019 
</div>
</footer>

<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$']]}});</script>
<script src="/js/easybook.js"></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-123344652-5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-123344652-5');
</script>


<script data-ad-client="ca-pub-8889449066804352" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.async = true;
  hm.src = "https://hm.baidu.com/hm.js?9b378145d7399199b371d067f4c8be96";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>




  </body>

</html>
