<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>使用Amazon Simple Queues Service (SQS)实现与AutoCAD远程交互 « NotBeCN</title>
  <meta name="description" content="                      亚马逊Amazon作为云计算的领跑者推出了很多云服务，我的同事Gopinath Taget在AutoCAD DevBlog上写了一篇文章介绍了SQS与AutoCAD的结合应用。SQS即可以理解为一个放在云上的消息队列，先进先出（FIFO）。【更正，云端的队列与我们常规的...">

  <link rel="stylesheet" href="/css/main.css">
  <link rel="canonical" href="https://notbe.cn/2016/09/15/weixin_34198881_90125711.html">
  <link rel="alternate" type="application/rss+xml" title="NotBeCN" href="https://notbe.cn/feed.xml" />
</head>


  <body>

    <div class="header-placeholder"></div>
<header class="header">
  <div class="wrapper">
    <div id="sidebar-toggle">TOC</div>
    <a class="site-title" href="/">NotBeCN</a>
    <nav class="site-nav">
      
        
        <a class="page-link" href="/about/" target="_blank">关于</a>
      
        
        <a class="page-link" href="https://uzshare.com" target="_blank">社区</a>
      
        
        <a class="page-link" href="/donate/" target="_blank">Donate</a>
      
        
        <a class="page-link" href="/games/shejiyazi/" target="_blank">射个鸭子</a>
      
    </nav>
  </div>
</header>


    <div class="page-content">
      <div class="wrapper">
        <div class="col-main">
          <div class="post">

  <header class="post-header">
    <h1 class="post-title">使用Amazon Simple Queues Service (SQS)实现与AutoCAD远程交互</h1>
    <p class="post-meta">Sep 15, 2016</p>
  </header>

  <article class="post-content">
    <div id="article_content" class="article_content clearfix csdn-tracking-statistics" data-pid="blog" data-mod="popu_307" data-dsm="post"> 
 <link rel="stylesheet" href="https://csdnimg.cn/release/phoenix/template/css/ck_htmledit_views-f57960eb32.css"> 
 <link rel="stylesheet" href="https://csdnimg.cn/release/phoenix/template/css/ck_htmledit_views-f57960eb32.css"> 
 <div class="htmledit_views" id="content_views"> 
  <div class="content-detail markdown-body"> 
   <h1 style="font-size:14.7px;color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;"><br></h1> 
   <div class="blogpost-body" style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;"> 
    <p style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">亚马逊Amazon作为云计算的领跑者推出了很多云服务，我的同事Gopinath Taget在</span><a href="http://adndevblog.typepad.com/autocad/" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><span style="line-height:1.5;font-size:x-small;">AutoCAD DevBlog</span></a><span style="line-height:1.5;font-size:x-small;">上写了</span><a href="http://adndevblog.typepad.com/autocad/2012/03/using-amazon-simple-queues-service-sqs-with-autocad-and-other-autodesk-products.html" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><span style="line-height:1.5;font-size:x-small;">一篇文章介绍了SQS与AutoCAD的结合应用</span></a><span style="line-height:1.5;font-size:x-small;">。SQS即可以理解为一个放在云上的消息队列，<span style="line-height:1.5;text-decoration:line-through;">先进先出（FIFO）</span>。【更正，云端的队列与我们常规的队列稍有不同，不能保证顺序是严格的先进先出(FIFO)，你从后面的演示例子就可以看出，出队列的顺序可能和进队列时不一样】保存在队列中的消息有一定时间的存活期。通过SQS，我们可以实现位于不同地方的不同程序在不同的时间内进行通信。 比如我可以从位于北京的一个普通桌面程序发送消息到亚马逊简单队列服务（SQS），发送完成后即可退出。其后位于北美的AutoCAD应用程序可以通过读取存储到SQS上的消息来完成北京发出的指令。</span></p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">要使用Amazon SQS服务，你需要首先注册一亚马逊云服务账号，现在亚马逊提供了为期一年的免费服务。你可以参考峻祁连的另一片文章《</span><a href="http://www.cnblogs.com/junqilian/archive/2010/11/07/1871348.html" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><span style="line-height:1.5;font-size:x-small;">免费的云技术平台--亚马逊WEB服务AWS提供免费方式</span></a><span style="line-height:1.5;font-size:x-small;">》。亚马逊提供了几种SDK，包括Java, Python, .net. 这里使用.net来掩饰。AWS .NET SDK可以从</span><a href="http://aws.amazon.com/sdkfornet/" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><span style="line-height:1.5;font-size:x-small;">这里下载</span></a><span style="line-height:1.5;font-size:x-small;">。安装好AWS .NET SDK后可以通过添加到AWSSDK.dll的引用来调用AWS提供的服务。</span></p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">下面我们就来模拟这个过程。首先建立一个普通的windows form应用程序作为发送端。添加到AWSSDK.dll的引用，这个dll位于C:\Program Files (x86)\AWS SDK for .NET\bin目录下。</span></p> 
    <p style="line-height:1.5;"><a href="http://images.cnblogs.com/cnblogs_com/junqilian/201203/201203251553384673.png" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><img title="image" src="https://images.cnblogs.com/cnblogs_com/junqilian/201203/201203251553437558.png" alt="image" width="244" height="207" style="border:0px;background-image:none;"></a></p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">首先需要创建一个对象来连接到Amazon SQS。连接到SQS需要你的Access Key和Secret Key。这两个key可以从</span><a href="https://aws-portal.amazon.com/gp/aws/securityCredentials" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><span style="line-height:1.5;font-size:x-small;">这里</span></a><span style="line-height:1.5;font-size:x-small;">找到。可以通过下面的方式把AccessKey和Secret Key以写在代码中。</span></p> 
    <blockquote style="background-image:none;border:2px solid rgb(239,239,239);">
     <pre><code class="language-csharp">AmazonSQS sqs = AWSClientFactory.CreateAmazonSQSClient(
    &lt;Access Key placeholder&gt;,  
    &lt;Secret Key placeholder&gt;);</code></pre>
    </blockquote> 
    <p style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">更好的方式是写在配置文件App.Config中，如下：</span></p> 
    <blockquote style="background-image:none;border:2px solid rgb(239,239,239);">
     <pre><code class="language-csharp"><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">&lt;?</span><span class="html" style="line-height:1.5;color:rgb(128,0,0);">xml</span> <span class="attr" style="line-height:1.5;color:rgb(255,0,0);">version</span><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">="1.0"</span> <span class="attr" style="line-height:1.5;color:rgb(255,0,0);">encoding</span><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">="utf-8"</span> ?<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">&gt;</span>
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">&lt;</span><span class="html" style="line-height:1.5;color:rgb(128,0,0);">configuration</span><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">&gt;</span>
  <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">&lt;</span><span class="html" style="line-height:1.5;color:rgb(128,0,0);">appSettings</span><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">&gt;</span>
    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">&lt;</span><span class="html" style="line-height:1.5;color:rgb(128,0,0);">add</span> <span class="attr" style="line-height:1.5;color:rgb(255,0,0);">key</span><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">="AWSAccessKey"</span> <span class="attr" style="line-height:1.5;color:rgb(255,0,0);">value</span><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">="*****"</span><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">/&gt;</span>
    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">&lt;</span><span class="html" style="line-height:1.5;color:rgb(128,0,0);">add</span> <span class="attr" style="line-height:1.5;color:rgb(255,0,0);">key</span><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">="AWSSecretKey"</span> <span class="attr" style="line-height:1.5;color:rgb(255,0,0);">value</span><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">="*****"</span><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">/&gt;</span>
  <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">&lt;/</span><span class="html" style="line-height:1.5;color:rgb(128,0,0);">appSettings</span><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">&gt;</span>
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">&lt;/</span><span class="html" style="line-height:1.5;color:rgb(128,0,0);">configuration</span><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">&gt;</span></code></pre>
    </blockquote> 
    <p style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">这样在创建AmazonSQS对象时直接用如下语句即可。程序会从App.Config中查找相关的Key信息。</span></p> 
    <blockquote style="background-image:none;border:2px solid rgb(239,239,239);">
     <pre><code class="language-csharp"><span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//Create AzazomSQS client using information of appconfig.xml</span>
AmazonSQS sqsClient = AWSClientFactory.CreateAmazonSQSClient();</code></pre>
    </blockquote> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">这个发送端程序要完成的工作就是向远程的AutoCAD发送工作序列，其中有三个任务：</span></p> 
    <p style="line-height:1.5;"><span class="str" style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">"Say: Hello AutoCAD" : 在AutoCAD命令行中输出这个信息；</span></span></p> 
    <p style="line-height:1.5;"><span class="str" style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">"Action: drawline" ： 在AutoCAD中画一条线；</span></span></p> 
    <p style="line-height:1.5;"><span class="str" style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">"Action: drawcircle" ： 在AutoCAD中画一圆。</span></span></p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">下面是发送端的完整代码：</span></p> 
    <blockquote style="background-image:none;border:2px solid rgb(239,239,239);">
     <pre><code class="language-csharp"><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> System;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> System.Collections.Generic;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> System.ComponentModel;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> System.Data;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> System.Drawing;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> System.Linq;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> System.Text;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> System.Windows.Forms;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> Amazon;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> Amazon.SQS;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> Amazon.SQS.Model;

<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">namespace</span> SQS_Sender
{
    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">public</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">partial</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">class</span> Form1 : Form
    {
        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">public</span> Form1()
        {
            InitializeComponent();
        }

        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">private</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">void</span> button1_Click(<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">object</span> sender, EventArgs e)
        {
            <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//Create AzazomSQS client using information of appconfig.xml</span>
            AmazonSQS sqsClient = AWSClientFactory.CreateAmazonSQSClient();
            <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//AmazonSQS sqs =</span>
            <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">// AWSClientFactory.CreateAmazonSQSClient(</span>
            <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">// &lt;Access Key placeholder&gt;, </span>
            <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">// &lt;Secret Key placeholder&gt;</span>
            <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">// );</span>

            <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">try</span>
            {
                <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//Create a queue if it does not exits</span>
                CreateQueueRequest sqsRequest = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> CreateQueueRequest();
                sqsRequest.QueueName = <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"AutoCADJobQueue"</span>;
                CreateQueueResponse sqsResponse = sqsClient.CreateQueue(sqsRequest);
                
                <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">string</span> myQueueUrl = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">string</span>.Empty; ;
                <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (sqsResponse.IsSetCreateQueueResult())
                {
                    myQueueUrl = sqsResponse.CreateQueueResult.QueueUrl;
                }

                <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//post a message to the queue</span>
                SendMessage(sqsClient, myQueueUrl, <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"Say: Hello AutoCAD"</span>);
                SendMessage(sqsClient, myQueueUrl, <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"Action: drawline"</span>);
                SendMessage(sqsClient, myQueueUrl,<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"Action: drawcircle"</span>);
                
            }
            <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">catch</span> (AmazonSQSException aEx)
            {
                MessageBox.Show(aEx.Message);
               
            }

        }

        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">private</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">static</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">void</span> SendMessage(AmazonSQS sqsClient, 
                                        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">string</span> myQueueUrl, 
                                        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">string</span> messageBody)
        {
            SendMessageRequest sendMsgRequest = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> SendMessageRequest();
            sendMsgRequest.QueueUrl = myQueueUrl;
            sendMsgRequest.MessageBody = messageBody;
            sqsClient.SendMessage(sendMsgRequest);
        }
    }
}
</code></pre>
    </blockquote> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">下面完成接收端。接收端一个AutoCAD插件，我们可以利用</span><a href="http://images.autodesk.com/adsk/files/AutoCAD_2010-2012_dotNET_Wizards.zip" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><span style="line-height:1.5;font-size:x-small;">AutoCAD 2010-2012 dotNet Wizards.zip</span></a><span style="line-height:1.5;font-size:x-small;">来创建一个插件模版，然后添加到AWSSDK.dll的引用。</span></p> 
    <p style="line-height:1.5;"><a href="http://images.cnblogs.com/cnblogs_com/junqilian/201203/201203251553453946.png" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><img title="image" src="https://images.cnblogs.com/cnblogs_com/junqilian/201203/201203251553472112.png" alt="image" width="229" height="361" style="border:0px;background-image:none;"></a></p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;">直接贴出完整代码如下：</p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <blockquote style="background-image:none;border:2px solid rgb(239,239,239);"> 
     <pre><code class="language-csharp"><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> System;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> Autodesk.AutoCAD.ApplicationServices;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> Autodesk.AutoCAD.DatabaseServices;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> Autodesk.AutoCAD.EditorInput;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> Autodesk.AutoCAD.Geometry;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> Autodesk.AutoCAD.Runtime;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> System.Collections.Generic;

<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> Amazon;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> Amazon.SQS;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> Amazon.SQS.Model;

<span class="rem" style="line-height:1.5;color:rgb(0,128,0);">// This line is not mandatory, but improves loading performances</span>
[assembly: CommandClass(<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">typeof</span>(SQS_AutoCADReceiver.MyCommands))]

<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">namespace</span> SQS_AutoCADReceiver
{

    <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">// This class is instantiated by AutoCAD for each document when</span>
    <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">// a command is called by the user the first time in the context</span>
    <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">// of a given document. In other words, non static data in this class</span>
    <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">// is implicitly per-document!</span>
    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">public</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">class</span> MyCommands
    {
        [CommandMethod(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"DoJobFromCloud"</span>,CommandFlags.Modal)]
        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">public</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">void</span> DoJobFromCloud() <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//this method can be any name</span>
        {
            Document doc = Application.DocumentManager.MdiActiveDocument;
            Database db = doc.Database;
            Editor ed = doc.Editor;

            <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//get the queue client</span>
            AmazonSQS sqsClient = AWSClientFactory.CreateAmazonSQSClient(
                <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"&lt;your access key&gt;"</span>,
                <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"&lt;your secret key&gt;"</span>
                );

            <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">try</span>
            {
                <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">string</span> myQueueUrl = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">string</span>.Empty;

                <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//checking whether the queue exits or not</span>
                ListQueuesRequest lstQueueRequest = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> ListQueuesRequest();
                ListQueuesResponse lstQueueResponse = sqsClient.ListQueues(lstQueueRequest);
                <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (lstQueueResponse.IsSetListQueuesResult())
                {
                    ListQueuesResult listQueueResult = lstQueueResponse.ListQueuesResult;

                    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">foreach</span> (<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">string</span> queueUrl <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">in</span> listQueueResult.QueueUrl)
                    {
                        ed.WriteMessage(queueUrl+ <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"\n"</span>);
                        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (queueUrl.Contains(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"AutoCADJobQueue"</span>))
                        {
                            myQueueUrl = queueUrl;
                        }   
                    }
                }

                <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (myQueueUrl.Length &gt; 0) <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//The queue exits</span>
                {
                    <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//Get the message number in the queue</span>
                    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">int</span> numMessage = GetMessageNumber(sqsClient, myQueueUrl);

                    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (numMessage &gt; 0)
                    {
                        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">do</span>
                        {
                            <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//receive a message</span>
                            ReceiveMessageRequest receiveReq = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> ReceiveMessageRequest();
                            receiveReq.QueueUrl = myQueueUrl;
                            ReceiveMessageResponse receiveRes = sqsClient.ReceiveMessage(receiveReq);

                            <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (receiveRes.IsSetReceiveMessageResult())
                            {
                                <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">foreach</span> (Message msg <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">in</span> receiveRes.ReceiveMessageResult.Message)
                                {
                                    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (msg.IsSetBody())
                                    {
                                        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (msg.Body.StartsWith(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"Say"</span>))
                                        {
                                            <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//print the message in AutoCAD</span>
                                            ed.WriteMessage(msg.Body + <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"\n"</span>);
                                        }
                                        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (msg.Body.StartsWith(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"Action"</span>))
                                        {
                                            <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (msg.Body == <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"Action: drawline"</span>)
                                            {
                                                <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//draw a line in AutoCAD</span>
                                                DrawLine();
                                                ed.WriteMessage(msg.Body + <span class="str" style="line-height:1.5;color:rgb(0,96,128);">" executed!\n"</span>);
                                            }
                                            <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (msg.Body == <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"Action: drawcircle"</span>)
                                            {
                                                <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//draw a circle in AutoCAD</span>
                                                DrawCircle();
                                                ed.WriteMessage(msg.Body + <span class="str" style="line-height:1.5;color:rgb(0,96,128);">" executed!\n"</span>);
                                            }
                                        }
                                    }

                                    <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//delete the message from queue, </span>
                                    <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//since we have aleady worked on it</span>
                                    DeleteMessageRequest delMsgRequest = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> DeleteMessageRequest();
                                    delMsgRequest.QueueUrl = myQueueUrl;
                                    delMsgRequest.ReceiptHandle = msg.ReceiptHandle;
                                    sqsClient.DeleteMessage(delMsgRequest);
                                }
                            }

                            numMessage = GetMessageNumber(sqsClient, myQueueUrl);
                        } <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">while</span> (numMessage &gt; 0);
                    }


                }


            }
            <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">catch</span> (AmazonSQSException aEx)
            {
                ed.WriteMessage(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"\n Error: "</span> + aEx.Message);
            }

        }

        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">private</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">static</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">int</span> GetMessageNumber(AmazonSQS sqsClient, <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">string</span> myQueueUrl)
        {
            <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">int</span> numMessage = 0;
            GetQueueAttributesRequest req = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> GetQueueAttributesRequest();
            req.AttributeName.Add(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"All"</span>);
            req.QueueUrl = myQueueUrl;
            GetQueueAttributesResponse res = sqsClient.GetQueueAttributes(req);

            <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (res.IsSetGetQueueAttributesResult())
            {
                GetQueueAttributesResult attResult = res.GetQueueAttributesResult;
                numMessage = attResult.ApproximateNumberOfMessages;
            }
            <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">return</span> numMessage;
        }

        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">public</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">void</span> DrawCircle()
        {
            Document doc = Application.DocumentManager.MdiActiveDocument;
            Database db = doc.Database;

            <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> (Transaction trans = db.TransactionManager.StartTransaction())
            {
                BlockTable bt = trans.GetObject(db.BlockTableId, OpenMode.ForWrite) <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">as</span> BlockTable;
                BlockTableRecord modelSpace = trans.GetObject(bt[BlockTableRecord.ModelSpace], OpenMode.ForWrite) </code></pre> 
     <pre><code class="language-csharp">                                           <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">as</span> BlockTableRecord;

                <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> (Circle c = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> Circle())
                {
                    c.Center = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> Point3d(0, 0, 0);
                    c.Radius = 10;
                    modelSpace.AppendEntity(c);
                    trans.AddNewlyCreatedDBObject(c, <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">true</span>);
                }

                trans.Commit();
                
            }
        }

        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">public</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">void</span> DrawLine()
        {
            Document doc = Application.DocumentManager.MdiActiveDocument;
            Database db = doc.Database;

            <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> (Transaction trans = db.TransactionManager.StartTransaction())
            {
                BlockTable bt = trans.GetObject(db.BlockTableId, OpenMode.ForWrite) <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">as</span> BlockTable;
                BlockTableRecord modelSpace = trans.GetObject(bt[BlockTableRecord.ModelSpace], OpenMode.ForWrite) </code></pre> 
     <pre><code class="language-csharp">                                           <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">as</span> BlockTableRecord;

                <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> (Line ln = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> Line())
                {
                    ln.StartPoint = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> Point3d(0,0,0);
                    ln.EndPoint = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> Point3d(10, 10, 0);
                    modelSpace.AppendEntity(ln);
                    trans.AddNewlyCreatedDBObject(ln, <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">true</span>);
                }

                trans.Commit();

            }
        }

    }

}
</code></pre> 
    </blockquote> 
    <p style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">下面是在AutoCAD中的运行结果：</span></p> 
    <p style="line-height:1.5;"><a href="http://images.cnblogs.com/cnblogs_com/junqilian/201203/201203251553497944.png" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><img title="image" src="https://images.cnblogs.com/cnblogs_com/junqilian/201203/201203251553526808.png" alt="image" width="450" height="574" style="border:0px;background-image:none;"></a></p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">你觉得还有哪些情形可以使用Amazon简单队列服务（SQS）？欢迎评论大家一起讨论。</span></p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;"><span style="line-height:1.5;font-size:x-small;">源码下载：<a title="http://dl.dropbox.com/u/48146765/SQS_AutoCAD.zip" href="http://dl.dropbox.com/u/48146765/SQS_AutoCAD.zip" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;">http://dl.dropbox.com/u/48146765/SQS_AutoCAD.zip</a>　</span></p> 
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    作者：
    <a href="http://junqilian.cnblogs.com/" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;">峻祁连</a>
    <br> 邮箱：junqilian@163.com&nbsp;
    <br> 出处：
    <a href="http://junqilian.cnblogs.com/" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;">http://junqilian.cnblogs.com</a>&nbsp;
    <br> 转载请保留此信息。
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    <br>
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    <br>
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    <br>
   </div> 
   <div> 
    <font color="#4b4b4b">本文转自峻祁连. Moving to Cloud/Mobile博客园博客，原文链接：http://www.cnblogs.com/junqilian/archive/2012/03/28/Amazon_SQS_AutoCAD.html</font>
    <span style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;">，如需转载请自行联系原作者</span> 
   </div> 
  </div> 
 </div> 
</div>
  </article>
  
  




</div>

        </div>
        <div class="col-second">
          <div class="col-box col-box-author">
  <img class="avatar" src="https://uzstatic-360cdn.belost.xyz/theme/default/images/logo.png" alt="柚子社区">
  <div class="col-box-title name">NotBeCN</div>
  <!-- <p>最新资讯</p> -->
  <p class="contact">
    
    <a href="mailto:fandyvon@163.com" target="_blank">邮箱</a>
    
    <a href="https://uzshare.com" target="_blank">柚子社区</a>
    
    <a href="https://uzzz.org" target="_blank">找组织</a>
    
  </p>
</div>

<div class="col-box">
  <div class="col-box-title">最新</div>
  <ul class="post-list">
    
      <li><a class="post-link" href="/2019/05/14/zxh1220_90138586.html">[原创软件] [软件发布] 定时备份文件发送邮箱，不再怕数据丢失了</a></li>
    
      <li><a class="post-link" href="/2019/05/14/weixin_45037290_90140056.html">Get智能写作满月记 ——产品篇</a></li>
    
      <li><a class="post-link" href="/2019/05/14/nulio__90138386.html">《深度探索C++对象模型》..............</a></li>
    
      <li><a class="post-link" href="/2019/05/13/qq_41248707_90140031.html">mysql 多表联查之连接查询</a></li>
    
      <li><a class="post-link" href="/2019/05/13/qq_21122683_90125902.html">golang基础(二)</a></li>
    
      <li><a class="post-link" href="/2019/05/13/1557726108256.html">今日份的PTA刷题</a></li>
    
      <li><a class="post-link" href="/2019/05/12/zzzfffei_90137366.html">Android之折线图</a></li>
    
      <li><a class="post-link" href="/2019/05/12/zzzfffei_90136638.html">Android之实现选中时改变样式</a></li>
    
  </ul>
</div>

<div class="col-box post-toc hide">
  <div class="col-box-title">目录</div>
</div>

<div class="col-box">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- right_sidebar -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8889449066804352"
       data-ad-slot="2081363239"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>


        </div>
      </div>
    </div>

    <footer class="footer">
<div class="wrapper">
&copy; 2019 
</div>
</footer>

<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$']]}});</script>
<script src="/js/easybook.js"></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-123344652-5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-123344652-5');
</script>


<script data-ad-client="ca-pub-8889449066804352" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.async = true;
  hm.src = "https://hm.baidu.com/hm.js?9b378145d7399199b371d067f4c8be96";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>




  </body>

</html>
