<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>AutoCAD中程序创建Ribbon界面执行AutoCAD命令 « NotBeCN</title>
  <meta name="description" content="                      在基于AutoCAD做二次开发时，常见的教程讲的都是在DLL中定义一些自定义命令，然后通过netload命令加载这个DLL，通过执行自定义命令的方式来执行我们的自定义功能。这样的方式在在学习中是显得很简单，但用在正式产品中就显得太业余了，没有专业精神。当然更profes...">

  <link rel="stylesheet" href="/css/main.css">
  <link rel="canonical" href="https://notbe.cn/2017/03/08/weixin_34234823_90117855.html">
  <link rel="alternate" type="application/rss+xml" title="NotBeCN" href="https://notbe.cn/feed.xml" />
</head>


  <body>

    <div class="header-placeholder"></div>
<header class="header">
  <div class="wrapper">
    <div id="sidebar-toggle">TOC</div>
    <a class="site-title" href="/">NotBeCN</a>
    <nav class="site-nav">
      
        
        <a class="page-link" href="/about/" target="_blank">关于</a>
      
        
        <a class="page-link" href="https://uzshare.com" target="_blank">社区</a>
      
        
        <a class="page-link" href="/donate/" target="_blank">Donate</a>
      
        
        <a class="page-link" href="/games/shejiyazi/" target="_blank">射个鸭子</a>
      
    </nav>
  </div>
</header>


    <div class="page-content">
      <div class="wrapper">
        <div class="col-main">
          <div class="post">

  <header class="post-header">
    <h1 class="post-title">AutoCAD中程序创建Ribbon界面执行AutoCAD命令</h1>
    <p class="post-meta">Mar 8, 2017</p>
  </header>

  <article class="post-content">
    <div id="article_content" class="article_content clearfix csdn-tracking-statistics" data-pid="blog" data-mod="popu_307" data-dsm="post"> 
 <link rel="stylesheet" href="https://csdnimg.cn/release/phoenix/template/css/ck_htmledit_views-f57960eb32.css"> 
 <link rel="stylesheet" href="https://csdnimg.cn/release/phoenix/template/css/ck_htmledit_views-f57960eb32.css"> 
 <div class="htmledit_views" id="content_views"> 
  <div class="content-detail markdown-body"> 
   <h1 style="font-size:14.7px;color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;"><br></h1> 
   <div class="blogpost-body" style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;"> 
    <p style="line-height:1.5;">在基于AutoCAD做二次开发时，<a href="http://www.cnblogs.com/junqilian/archive/2012/04/23/2466723.html" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;">常见的教程</a>讲的都是在DLL中定义一些自定义命令，然后通过netload命令加载这个DLL，通过执行自定义命令的方式来执行我们的自定义功能。这样的方式在在学习中是显得很简单，但用在正式产品中就显得太业余了，没有专业精神。当然更professional的当然是和AutoCAD一样，提供一些基于Ribbon的用户界面来调用我们的自定义功能才好。多啰嗦一句，这个方法同样适用基于AutoCAD的其他产品，比如Map 3D和Civil 3D。下面就讲讲如何实现创建Ribbon用户界面。</p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;">首先了解一下Ribbon的概念，下图是AutoCAD的一个Ribbon界面截图，它有一些Tab组成，比如Home，Insert等等；在一个Tab里面又有不同的Panel组成，即竖线分割的部分；panel里面就是button了，这些button来执行具体的功能。不是很准确，我理解大概就是这样回事了。：）</p> 
    <p style="line-height:1.5;"><a href="http://images.cnblogs.com/cnblogs_com/junqilian/201206/201206181534423884.png" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><img title="image" alt="image" src="https://images.cnblogs.com/cnblogs_com/junqilian/201206/201206181537467618.png" width="937" height="210" style="border:0px;background-image:none;"></a></p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;">下面来通过程序创建一个tab，在这个tab里面加两个panel，在panel里面放两个button来执行自定义的AutoCAD命令。</p> 
    <p style="line-height:1.5;">新建一个class类库工程，需要添加的引用包括：</p> 
    <p style="line-height:1.5;">acmgd</p> 
    <p style="line-height:1.5;">acdbmgd</p> 
    <p style="line-height:1.5;">acCoreMgd(对于AutoCAD 2013)</p> 
    <p style="line-height:1.5;">acCui</p> 
    <p style="line-height:1.5;">AcWindows</p> 
    <p style="line-height:1.5;">AdWindows</p> 
    <p style="line-height:1.5;">下面是代码片段：</p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <pre><code class="language-csharp">    
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);"> private</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">const</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">string</span> MY_TAB_ID = <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"MY_TAB_ID"</span>;

    [CommandMethod(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"addMyRibbon"</span>)]
    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">public</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">void</span> createRibbon()
    {
      Autodesk.Windows.RibbonControl ribCntrl =
                Autodesk.AutoCAD.Ribbon.RibbonServices.RibbonPaletteSet.RibbonControl;
      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//can also be Autodesk.Windows.ComponentManager.Ribbon; </span>

      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//add the tab</span>
      RibbonTab ribTab = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> RibbonTab();
      ribTab.Title = <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"My custom tab"</span>;
      ribTab.Id = MY_TAB_ID;
      ribCntrl.Tabs.Add(ribTab);

      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//create and add both panels</span>
      addPanel1(ribTab);
      addPanel2(ribTab);

      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//set as active tab</span>
      ribTab.IsActive = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">true</span>;
    }

    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">private</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">void</span> addPanel2(RibbonTab ribTab)
    {
      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//throw new NotImplementedException();</span>
    }

    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">private</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">void</span> addPanel1(RibbonTab ribTab)
    {
      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//throw new NotImplementedException();</span>
    }</code></pre> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;">通过这些代码，应该已经可以创建一个空白的Tab，并把他设置当前活动Tab，如图：</p> 
    <p style="line-height:1.5;"><a href="http://images.cnblogs.com/cnblogs_com/junqilian/201206/201206181537554672.png" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><img title="image" alt="image" src="https://images.cnblogs.com/cnblogs_com/junqilian/201206/201206181538383688.png" width="613" height="108" style="border:0px;background-image:none;"></a></p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;">现在往这个Tab里面添加一个Panel，然后加入一个button来执行我的自定义命令。</p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <pre><code class="language-csharp">    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">private</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">const</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">string</span> MY_TAB_ID = <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"MY_TAB_ID"</span>;

    [CommandMethod(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"addMyRibbon"</span>)]
    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">public</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">void</span> createRibbon()
    {
      Autodesk.Windows.RibbonControl ribCntrl =
                Autodesk.AutoCAD.Ribbon.RibbonServices.RibbonPaletteSet.RibbonControl;
      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//can also be Autodesk.Windows.ComponentManager.Ribbon; </span>

      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//add the tab</span>
      RibbonTab ribTab = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> RibbonTab();
      ribTab.Title = <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"My custom tab"</span>;
      ribTab.Id = MY_TAB_ID;
      ribCntrl.Tabs.Add(ribTab);

      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//create and add both panels</span>
      addPanel1(ribTab);
      addPanel2(ribTab);

      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//set as active tab</span>
      ribTab.IsActive = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">true</span>;
    }

    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">private</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">void</span> addPanel2(RibbonTab ribTab)
    {
      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//create the panel source</span>
      RibbonPanelSource ribPanelSource = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> RibbonPanelSource();
      ribPanelSource.Title = <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"Edit Registry"</span>;

      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//create the panel</span>
      RibbonPanel ribPanel = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> RibbonPanel();
      ribPanel.Source = ribPanelSource;
      ribTab.Panels.Add(ribPanel);

      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//create button1</span>
      RibbonButton ribButtonDrawCircle = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> RibbonButton();
      ribButtonDrawCircle.Text = <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"My Draw Circle"</span>;
      ribButtonDrawCircle.ShowText = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">true</span>;
      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//pay attention to the SPACE after the command name</span>
      ribButtonDrawCircle.CommandParameter = <span class="str" style="line-height:1.5;color:rgb(0,96,128);">"DrawCircle "</span>;
      ribButtonDrawCircle.CommandHandler = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> AdskCommandHandler();

      ribPanelSource.Items.Add(ribButtonDrawCircle);

    }

    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">private</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">void</span> addPanel1(RibbonTab ribTab)
    {
      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//throw new NotImplementedException();</span>
    }

    [CommandMethod(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"DrawCircle"</span>)]
    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">public</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">void</span> DrawCircle()
    {
      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//画个圆，实现在此略去，这不是这篇blog的重点。</span>
    }
</code></pre> 
    <p style="line-height:1.5;">注意上面的代码中我定义了一个ribButtonDrawCircle，指定他的CommandParameter为我的自定义命令名“DrawCircle”，并且指定他的CommandHandler 是AdskCommandHandler。这里的AdskCommandHandler是一个自定义的类，需要实现System.Windows.Input.ICommand接口。实现的方法就是在Execute时把commandParameter发送到AutoCAD命令行窗口执行。代码如下：</p> 
    <pre><code class="language-csharp"><span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> System;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> System.Collections.Generic;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> System.Linq;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> System.Text;
<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> Autodesk.Windows;


<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">namespace</span> AutoCAD_Debugger
{
  <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">class</span> AdskCommandHandler : System.Windows.Input.ICommand
  {
    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">public</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">bool</span> CanExecute(<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">object</span> parameter)
    {
      <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">return</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">true</span>;
    }

    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">public</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">event</span> EventHandler CanExecuteChanged;

    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">public</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">void</span> Execute(<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">object</span> parameter)
    {
      <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//is from Ribbon Button</span>
      RibbonButton ribBtn = parameter <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">as</span> RibbonButton;
      <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (ribBtn != <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">null</span>)
      {
        <span class="rem" style="line-height:1.5;color:rgb(0,128,0);">//execute the command </span>
        Autodesk.AutoCAD.ApplicationServices.Application
          .DocumentManager.MdiActiveDocument
          .SendStringToExecute(
             (<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">string</span>)ribBtn.CommandParameter, <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">true</span>, <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">false</span>, <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">true</span>);
      }
    }
  }
}
</code></pre> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;">执行结果如下图。注意如果你在测试是发现你的button只是把命令字符串发送到了AutoCAD命令行但没有执行，必须按回车才能执行，那你多半是忽略了CommandParameter 后面那个空格！</p> 
    <p style="line-height:1.5;"><a href="http://images.cnblogs.com/cnblogs_com/junqilian/201206/20120618153909861.png" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><img title="image" alt="image" src="https://images.cnblogs.com/cnblogs_com/junqilian/201206/201206181539263168.png" width="552" height="349" style="border:0px;background-image:none;"></a></p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;">好了，基本过程应该就是这样，当然我们还可以为button添加图标，让他更好看一点。下来峻祁连将再介绍如何让AutoCAD自动就自动加载这个Ribbon菜单，这个就更方便了，敬请期待。</p> 
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    作者：
    <a href="http://junqilian.cnblogs.com/" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;">峻祁连</a>
    <br> 邮箱：junqilian@163.com&nbsp;
    <br> 出处：
    <a href="http://junqilian.cnblogs.com/" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;">http://junqilian.cnblogs.com</a>&nbsp;
    <br> 转载请保留此信息。
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    <br>
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    <br>
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    <br>
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    <br>
   </div> 
   <div> 
    <font color="#4b4b4b">本文转自峻祁连. Moving to Cloud/Mobile博客园博客，原文链接：http://www.cnblogs.com/junqilian/archive/2012/06/18/2553662.html</font>
    <span style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;">，如需转载请自行联系原作者</span> 
   </div> 
  </div> 
 </div> 
</div>
  </article>
  
  




</div>

        </div>
        <div class="col-second">
          <div class="col-box col-box-author">
  <img class="avatar" src="https://uzstatic-360cdn.belost.xyz/theme/default/images/logo.png" alt="柚子社区">
  <div class="col-box-title name">NotBeCN</div>
  <!-- <p>最新资讯</p> -->
  <p class="contact">
    
    <a href="mailto:fandyvon@163.com" target="_blank">邮箱</a>
    
    <a href="https://uzshare.com" target="_blank">柚子社区</a>
    
    <a href="https://uzzz.org" target="_blank">找组织</a>
    
  </p>
</div>

<div class="col-box">
  <div class="col-box-title">最新</div>
  <ul class="post-list">
    
      <li><a class="post-link" href="/2019/05/14/zxh1220_90138586.html">[原创软件] [软件发布] 定时备份文件发送邮箱，不再怕数据丢失了</a></li>
    
      <li><a class="post-link" href="/2019/05/14/weixin_45037290_90140056.html">Get智能写作满月记 ——产品篇</a></li>
    
      <li><a class="post-link" href="/2019/05/14/nulio__90138386.html">《深度探索C++对象模型》..............</a></li>
    
      <li><a class="post-link" href="/2019/05/13/qq_41248707_90140031.html">mysql 多表联查之连接查询</a></li>
    
      <li><a class="post-link" href="/2019/05/13/qq_21122683_90125902.html">golang基础(二)</a></li>
    
      <li><a class="post-link" href="/2019/05/13/1557726108256.html">今日份的PTA刷题</a></li>
    
      <li><a class="post-link" href="/2019/05/12/zzzfffei_90137366.html">Android之折线图</a></li>
    
      <li><a class="post-link" href="/2019/05/12/zzzfffei_90136638.html">Android之实现选中时改变样式</a></li>
    
  </ul>
</div>

<div class="col-box post-toc hide">
  <div class="col-box-title">目录</div>
</div>

<div class="col-box">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- right_sidebar -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8889449066804352"
       data-ad-slot="2081363239"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>


        </div>
      </div>
    </div>

    <footer class="footer">
<div class="wrapper">
&copy; 2019 
</div>
</footer>

<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$']]}});</script>
<script src="/js/easybook.js"></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-123344652-5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-123344652-5');
</script>


<script data-ad-client="ca-pub-8889449066804352" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.async = true;
  hm.src = "https://hm.baidu.com/hm.js?9b378145d7399199b371d067f4c8be96";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>




  </body>

</html>
