<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>自制三维建模软件（六）瓶子模型例程 « NotBeCN</title>
  <meta name="description" content="                        文章目录       概述         预备知识     模型     规格        一、构建轮廓         定义支持点     定义几何图形     定义拓扑结构     完成轮廓        二、构建瓶身         拉伸轮廓     倒角...">

  <link rel="stylesheet" href="/css/main.css">
  <link rel="canonical" href="https://notbe.cn/2019/05/12/jelatine_90139534.html">
  <link rel="alternate" type="application/rss+xml" title="NotBeCN" href="https://notbe.cn/feed.xml" />
</head>


  <body>

    <div class="header-placeholder"></div>
<header class="header">
  <div class="wrapper">
    <div id="sidebar-toggle">TOC</div>
    <a class="site-title" href="/">NotBeCN</a>
    <nav class="site-nav">
      
        
        <a class="page-link" href="/about/" target="_blank">关于</a>
      
        
        <a class="page-link" href="https://uzshare.com" target="_blank">社区</a>
      
        
        <a class="page-link" href="/donate/" target="_blank">Donate</a>
      
        
        <a class="page-link" href="/games/shejiyazi/" target="_blank">射个鸭子</a>
      
    </nav>
  </div>
</header>


    <div class="page-content">
      <div class="wrapper">
        <div class="col-main">
          <div class="post">

  <header class="post-header">
    <h1 class="post-title">自制三维建模软件（六）瓶子模型例程</h1>
    <p class="post-meta">May 12, 2019</p>
  </header>

  <article class="post-content">
    <div id="article_content" class="article_content clearfix csdn-tracking-statistics" data-pid="blog" data-mod="popu_307" data-dsm="post">  
 <link rel="stylesheet" href="https://csdnimg.cn/release/phoenix/template/css/ck_htmledit_views-f57960eb32.css"> 
 <div id="content_views" class="markdown_views prism-atom-one-dark"> 
  <!-- flowchart 箭头图标 勿删 --> 
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
   <path stroke-linecap="round" d="M5,0 0,2.5 5,5z" id="raphael-marker-block" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></path>
  </svg> 
  <p></p>
  <div class="toc">
   <h3>文章目录</h3>
   <ul>
    <li><a href="#_2" rel="nofollow">概述</a></li>
    <ul>
     <li><a href="#_3" rel="nofollow">预备知识</a></li>
     <li><a href="#_5" rel="nofollow">模型</a></li>
     <li><a href="#_8" rel="nofollow">规格</a></li>
    </ul>
    <li><a href="#_24" rel="nofollow">一、构建轮廓</a></li>
    <ul>
     <li><a href="#_25" rel="nofollow">定义支持点</a></li>
     <li><a href="#_38" rel="nofollow">定义几何图形</a></li>
     <li><a href="#_49" rel="nofollow">定义拓扑结构</a></li>
     <li><a href="#_76" rel="nofollow">完成轮廓</a></li>
    </ul>
    <li><a href="#_95" rel="nofollow">二、构建瓶身</a></li>
    <ul>
     <li><a href="#_96" rel="nofollow">拉伸轮廓</a></li>
     <li><a href="#_117" rel="nofollow">倒角</a></li>
     <li><a href="#_137" rel="nofollow">添加瓶颈</a></li>
     <li><a href="#_153" rel="nofollow">创造中空的实体</a></li>
    </ul>
    <li><a href="#_185" rel="nofollow">三、构建螺纹</a></li>
    <ul>
     <li><a href="#_186" rel="nofollow">创建表面</a></li>
     <li><a href="#_200" rel="nofollow">定义二维曲线</a></li>
     <li><a href="#_236" rel="nofollow">创建边和线</a></li>
     <li><a href="#_256" rel="nofollow">构建螺纹</a></li>
    </ul>
    <li><a href="#_272" rel="nofollow">四、整合模型</a></li>
    <ul>
     <li><a href="#_285" rel="nofollow">五、实际效果</a></li>
    </ul>
    <li><a href="#_309" rel="nofollow">项目仓库</a></li>
   </ul>
  </div>
  <br> 在OpenCASCADE有一个例程，在
  <a href="https://www.opencascade.com/doc/occt-7.3.0/overview/html/occt__tutorial.html" rel="nofollow">官方帮助网站</a>中可以找到。程将教你如何使OpenCASCADE服务来进行三维建模。教程的目的不是描述所有的类，而是帮助你开始考虑将OpenCASCADE作为一种工具。
  <p></p> 
  <h1><a id="_2"></a>概述</h1> 
  <h2><a id="_3"></a>预备知识</h2> 
  <p>教程中需要有一定的C++的经验。从编程的角度来看，Open CASCADE的目的是用三维建模类、方法和函数来增强C++工具。所有这些资源的组合可以让你创建实际的应用程序。</p> 
  <h2><a id="_5"></a>模型</h2> 
  <p>为了演示三维建模工具包中提类的使用，我们将创建一个三维瓶子，如下图所示：<br> <img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512131701879.png" alt="在这里插入图片描述"></p> 
  <h2><a id="_8"></a>规格</h2> 
  <p>制定瓶子规格如下：</p> 
  <table> 
   <thead> 
    <tr> 
     <th>物件参数</th> 
     <th>参数名称</th> 
     <th>参数值</th> 
    </tr> 
   </thead> 
   <tbody> 
    <tr> 
     <td>瓶子高度</td> 
     <td>myHeight</td> 
     <td>70mm</td> 
    </tr> 
    <tr> 
     <td>瓶子宽度</td> 
     <td>myWidth</td> 
     <td>50mm</td> 
    </tr> 
    <tr> 
     <td>瓶子厚度</td> 
     <td>myThickness</td> 
     <td>30mm</td> 
    </tr> 
   </tbody> 
  </table>
  <p>此外，瓶子的底座将以笛卡尔坐标系的原点为中心。<br> <img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512132255437.png" alt="在这里插入图片描述"></p> 
  <p>通过以下四个步骤对瓶子建模：</p> 
  <ol> 
   <li>构建瓶子轮廓</li> 
   <li>构建瓶子瓶身</li> 
   <li>在瓶口上做螺纹</li> 
   <li>合并模型</li> 
  </ol> 
  <h1><a id="_24"></a>一、构建轮廓</h1> 
  <h2><a id="_25"></a>定义支持点</h2> 
  <p>首先创建轮廓的特征点及其坐标，如下面的(XOY)平面所示。这些点为几何形状的支持点。<br> <img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512135327248.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2plbGF0aW5l,size_16,color_FFFFFF,t_70" alt="在这里插入图片描述"></p> 
  <pre><code class="prism language-cpp">    <span class="token comment">// 轮廓：定义支持点</span>
    gp_Pnt <span class="token function">aPnt1</span><span class="token punctuation">(</span><span class="token operator">-</span>myWidth <span class="token operator">/</span> <span class="token number">2.</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    gp_Pnt <span class="token function">aPnt2</span><span class="token punctuation">(</span><span class="token operator">-</span>myWidth <span class="token operator">/</span> <span class="token number">2.</span><span class="token punctuation">,</span> <span class="token operator">-</span>myThickness <span class="token operator">/</span> <span class="token number">4.</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    gp_Pnt <span class="token function">aPnt3</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token operator">-</span>myThickness <span class="token operator">/</span> <span class="token number">2.</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    gp_Pnt <span class="token function">aPnt4</span><span class="token punctuation">(</span>myWidth <span class="token operator">/</span> <span class="token number">2.</span><span class="token punctuation">,</span> <span class="token operator">-</span>myThickness <span class="token operator">/</span> <span class="token number">4.</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    gp_Pnt <span class="token function">aPnt5</span><span class="token punctuation">(</span>myWidth <span class="token operator">/</span> <span class="token number">2.</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre> 
  <h2><a id="_38"></a>定义几何图形</h2> 
  <p>在前面定义的点的帮助下，您可以计算出瓶子轮廓几何的一部分。如图所示，它将由两个线段和一个圆弧组成。<br> <img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512142505474.png" alt="在这里插入图片描述"></p> 
  <pre><code class="prism language-cpp">    <span class="token comment">// 轮廓：定义几何图形</span>
    <span class="token function">Handle</span><span class="token punctuation">(</span>Geom_TrimmedCurve<span class="token punctuation">)</span> anArcOfCircle <span class="token operator">=</span> <span class="token function">GC_MakeArcOfCircle</span><span class="token punctuation">(</span>aPnt2<span class="token punctuation">,</span>aPnt3<span class="token punctuation">,</span>aPnt4<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token function">Handle</span><span class="token punctuation">(</span>Geom_TrimmedCurve<span class="token punctuation">)</span> aSegment1 <span class="token operator">=</span> <span class="token function">GC_MakeSegment</span><span class="token punctuation">(</span>aPnt1<span class="token punctuation">,</span> aPnt2<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token function">Handle</span><span class="token punctuation">(</span>Geom_TrimmedCurve<span class="token punctuation">)</span> aSegment2 <span class="token operator">=</span> <span class="token function">GC_MakeSegment</span><span class="token punctuation">(</span>aPnt4<span class="token punctuation">,</span> aPnt5<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre> 
  <h2><a id="_49"></a>定义拓扑结构</h2> 
  <p>现在已经创建了轮廓的一个部分的几何曲线，但这些曲线是独立的，彼此之间没有关系。为了简化建模，可以凭借这三条曲线制作为一个实体。这可以通过使用TopoDS包中定义的OCC的拓扑数据结构来实现：它定义了几何实体之间的关系，这些实体可以链接在一起来表示复杂的形状。TopoDS包的每个对象继承自TopoDS_Shape类，描述一个拓扑形状，如下图所示：</p> 
  <table> 
   <thead> 
    <tr> 
     <th>形状</th> 
     <th>Open CASCADE</th> 
     <th>类型描述</th> 
    </tr> 
   </thead> 
   <tbody> 
    <tr> 
     <td>Vertex</td> 
     <td>TopoDS_Vertex</td> 
     <td>零维空间形状，相当于几何中的一个点</td> 
    </tr> 
    <tr> 
     <td>Edge</td> 
     <td>TopoDS_Edge</td> 
     <td>与曲线相对应的一维形状，在每条曲线的每一个末端上都有一个顶点</td> 
    </tr> 
    <tr> 
     <td>Wire</td> 
     <td>TopoDS_Wire</td> 
     <td>由顶点连接的边的序列。</td> 
    </tr> 
    <tr> 
     <td>Face</td> 
     <td>TopoDS_Face</td> 
     <td>表面的一部分，以闭合的导线为界</td> 
    </tr> 
    <tr> 
     <td>Shell</td> 
     <td>TopoDS_Shell</td> 
     <td>由边连接的面集</td> 
    </tr> 
    <tr> 
     <td>Solid</td> 
     <td>TopoDS_Solid</td> 
     <td>由外壳包围的部分3D 空间</td> 
    </tr> 
    <tr> 
     <td>CompSolid</td> 
     <td>TopoDS_CompSolid</td> 
     <td>由面连接的一组固体</td> 
    </tr> 
    <tr> 
     <td>Compound</td> 
     <td>TopoDS_Compound</td> 
     <td>上述任何其他形状的集合</td> 
    </tr> 
   </tbody> 
  </table>
  <p>参照上表，要构建轮廓需要创建:</p> 
  <ul> 
   <li>之前创建的三条边（Edge）</li> 
   <li>一条有这些边的线（Wire）<br> <img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512144259711.png" alt="在这里插入图片描述"><br> 然而，TopoDS包只提供拓扑实体的数据结构。可以在BRepBuilderAPI包中找到用于计算标准拓扑对象的算法类。要创建一条边，可以使用BRepBuilderAPI_MakeEdge类来创建前面计算过的曲线：</li> 
  </ul> 
  <pre><code class="prism language-cpp">    <span class="token comment">// 轮廓：定义拓扑结构</span>
    TopoDS_Edge anEdge1 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeEdge</span><span class="token punctuation">(</span>aSegment1<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Edge anEdge2 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeEdge</span><span class="token punctuation">(</span>anArcOfCircle<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Edge anEdge3 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeEdge</span><span class="token punctuation">(</span>aSegment2<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Wire aWire  <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeWire</span><span class="token punctuation">(</span>anEdge1<span class="token punctuation">,</span> anEdge2<span class="token punctuation">,</span> anEdge3<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre> 
  <h2><a id="_76"></a>完成轮廓</h2> 
  <p>完成创建以上的线后，需要完成整个轮廓：</p> 
  <ul> 
   <li>通过反射现有的导线来计算新的线</li> 
   <li>将反射线添加到初始线<br> <img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512150009494.png" alt="在这里插入图片描述"></li> 
  </ul> 
  <pre><code class="prism language-cpp">    <span class="token comment">// 轮廓：完成轮廓</span>
    gp_Ax1 xAxis <span class="token operator">=</span> gp<span class="token operator">::</span><span class="token function">OX</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>    <span class="token comment">// 获得X轴</span>
    gp_Trsf aTrsf<span class="token punctuation">;</span>
    aTrsf<span class="token punctuation">.</span><span class="token function">SetMirror</span><span class="token punctuation">(</span>xAxis<span class="token punctuation">)</span><span class="token punctuation">;</span>
    BRepBuilderAPI_Transform <span class="token function">aBRepTrsf</span><span class="token punctuation">(</span>aWire<span class="token punctuation">,</span> aTrsf<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Shape aMirroredShape <span class="token operator">=</span> aBRepTrsf<span class="token punctuation">.</span><span class="token function">Shape</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Wire aMirroredWire <span class="token operator">=</span> TopoDS<span class="token operator">::</span><span class="token function">Wire</span><span class="token punctuation">(</span>aMirroredShape<span class="token punctuation">)</span><span class="token punctuation">;</span>
    BRepBuilderAPI_MakeWire mkWire<span class="token punctuation">;</span>
    mkWire<span class="token punctuation">.</span><span class="token function">Add</span><span class="token punctuation">(</span>aWire<span class="token punctuation">)</span><span class="token punctuation">;</span>
    mkWire<span class="token punctuation">.</span><span class="token function">Add</span><span class="token punctuation">(</span>aMirroredWire<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre> 
  <h1><a id="_95"></a>二、构建瓶身</h1> 
  <h2><a id="_96"></a>拉伸轮廓</h2> 
  <p>要计算瓶身，需要创建一个实体形状。最简单的方法是使用前面创建的轮廓，并沿着一个方向进行扫描。Open CASCADE的Prism功能最适合这项任务。它接受一个形状和一个方向作为输入，并根据以下规则生成一个新的形状：</p> 
  <table> 
   <thead> 
    <tr> 
     <th>形状</th> 
     <th>生成</th> 
    </tr> 
   </thead> 
   <tbody> 
    <tr> 
     <td>Vertex</td> 
     <td>Edge</td> 
    </tr> 
    <tr> 
     <td>Edge</td> 
     <td>Face</td> 
    </tr> 
    <tr> 
     <td>Wire</td> 
     <td>Shell</td> 
    </tr> 
    <tr> 
     <td>Face</td> 
     <td>Solid</td> 
    </tr> 
    <tr> 
     <td>Shell</td> 
     <td>Compound of Solids</td> 
    </tr> 
   </tbody> 
  </table>
  <p><img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512150646940.png" alt="在这里插入图片描述"></p> 
  <pre><code class="prism language-cpp">    <span class="token comment">// 瓶身：拉伸轮廓</span>
    TopoDS_Face myFaceProfile <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeFace</span><span class="token punctuation">(</span>myWireProfile<span class="token punctuation">)</span><span class="token punctuation">;</span>
    gp_Vec <span class="token function">aPrismVec</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> myHeight<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Shape myBody <span class="token operator">=</span> <span class="token function">BRepPrimAPI_MakePrism</span><span class="token punctuation">(</span>myFaceProfile<span class="token punctuation">,</span> aPrismVec<span class="token punctuation">)</span><span class="token punctuation">;</span>

</code></pre> 
  <h2><a id="_117"></a>倒角</h2> 
  <p>瓶身的边缘很锋利。要用圆脸替换它们，可以使用Open CASCADE的圆角功能。根据我们的需求，指定倒角必须：</p> 
  <ul> 
   <li>应用在形状的所有边缘</li> 
   <li>半径是myThickness / 12</li> 
  </ul> 
  <p><img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512151101522.png" alt="在这里插入图片描述"></p> 
  <pre><code class="prism language-cpp">    <span class="token comment">// 瓶身：倒角</span>
    BRepFilletAPI_MakeFillet <span class="token function">mkFillet</span><span class="token punctuation">(</span>myBody<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopExp_Explorer <span class="token function">anEdgeExplorer</span><span class="token punctuation">(</span>myBody<span class="token punctuation">,</span> TopAbs_EDGE<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">while</span><span class="token punctuation">(</span>anEdgeExplorer<span class="token punctuation">.</span><span class="token function">More</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
        TopoDS_Edge anEdge <span class="token operator">=</span> TopoDS<span class="token operator">::</span><span class="token function">Edge</span><span class="token punctuation">(</span>anEdgeExplorer<span class="token punctuation">.</span><span class="token function">Current</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">//Add edge to fillet algorithm</span>
        mkFillet<span class="token punctuation">.</span><span class="token function">Add</span><span class="token punctuation">(</span>myThickness <span class="token operator">/</span> <span class="token number">12.</span><span class="token punctuation">,</span> anEdge<span class="token punctuation">)</span><span class="token punctuation">;</span>
        anEdgeExplorer<span class="token punctuation">.</span><span class="token function">Next</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    myBody <span class="token operator">=</span> mkFillet<span class="token punctuation">.</span><span class="token function">Shape</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre> 
  <h2><a id="_137"></a>添加瓶颈</h2> 
  <p>要在瓶子上加一个颈，需要做一个圆柱体，然后把它和瓶身融合在一起。圆柱体安装在瓶身的顶部，半径为myThickness / 4，高度为和myHeight / 10<br> <img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512151537580.png" alt="在这里插入图片描述"></p> 
  <pre><code class="prism language-cpp">    <span class="token comment">// 瓶身：添加瓶颈</span>
    gp_Pnt <span class="token function">neckLocation</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> myHeight<span class="token punctuation">)</span><span class="token punctuation">;</span>
    gp_Dir neckAxis <span class="token operator">=</span> gp<span class="token operator">::</span><span class="token function">DZ</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    gp_Ax2 <span class="token function">neckAx2</span><span class="token punctuation">(</span>neckLocation<span class="token punctuation">,</span> neckAxis<span class="token punctuation">)</span><span class="token punctuation">;</span>
    Standard_Real myNeckRadius <span class="token operator">=</span> myThickness <span class="token operator">/</span> <span class="token number">4.</span><span class="token punctuation">;</span>
    Standard_Real myNeckHeight <span class="token operator">=</span> myHeight <span class="token operator">/</span> <span class="token number">10.</span><span class="token punctuation">;</span>
    BRepPrimAPI_MakeCylinder <span class="token function">MKCylinder</span><span class="token punctuation">(</span>neckAx2<span class="token punctuation">,</span> myNeckRadius<span class="token punctuation">,</span> myNeckHeight<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Shape myNeck <span class="token operator">=</span> MKCylinder<span class="token punctuation">.</span><span class="token function">Shape</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    myBody <span class="token operator">=</span> <span class="token function">BRepAlgoAPI_Fuse</span><span class="token punctuation">(</span>myBody<span class="token punctuation">,</span> myNeck<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre> 
  <h2><a id="_153"></a>创造中空的实体</h2> 
  <p>因为一个真正的瓶子是用来装液体材料的，所以应该从瓶子的顶部创建一个中空的实体。在OpenCASCADE中，被掏空的固体称为Thick Solid，其内部计算如下：</p> 
  <ul> 
   <li>从初始实体中移除一个或多个面，以获得被掏空实体的第一面墙W1。</li> 
   <li>在距离D处，从W1创建一个平行的墙W2。如果D是正的，W2将在初始实体的外面，否则它将在里面。</li> 
   <li>从W1和W2两面墙计算一个实体。<br> <img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512152023356.png" alt="在这里插入图片描述"></li> 
  </ul> 
  <pre><code class="prism language-cpp">    <span class="token comment">// 瓶身：创造中空的实体</span>
    TopoDS_Face   faceToRemove<span class="token punctuation">;</span>
    Standard_Real zMax <span class="token operator">=</span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">;</span>
    <span class="token keyword">for</span><span class="token punctuation">(</span>TopExp_Explorer <span class="token function">aFaceExplorer</span><span class="token punctuation">(</span>myBody<span class="token punctuation">,</span> TopAbs_FACE<span class="token punctuation">)</span><span class="token punctuation">;</span> aFaceExplorer<span class="token punctuation">.</span><span class="token function">More</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> aFaceExplorer<span class="token punctuation">.</span><span class="token function">Next</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
        TopoDS_Face aFace <span class="token operator">=</span> TopoDS<span class="token operator">::</span><span class="token function">Face</span><span class="token punctuation">(</span>aFaceExplorer<span class="token punctuation">.</span><span class="token function">Current</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// Check if &lt;aFace&gt; is the top face of the bottle's neck</span>
        <span class="token function">Handle</span><span class="token punctuation">(</span>Geom_Surface<span class="token punctuation">)</span> aSurface <span class="token operator">=</span> BRep_Tool<span class="token operator">::</span><span class="token function">Surface</span><span class="token punctuation">(</span>aFace<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span><span class="token punctuation">(</span>aSurface<span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">DynamicType</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">==</span> <span class="token function">STANDARD_TYPE</span><span class="token punctuation">(</span>Geom_Plane<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
            <span class="token function">Handle</span><span class="token punctuation">(</span>Geom_Plane<span class="token punctuation">)</span> aPlane <span class="token operator">=</span> <span class="token function">Handle</span><span class="token punctuation">(</span>Geom_Plane<span class="token punctuation">)</span><span class="token operator">::</span><span class="token function">DownCast</span><span class="token punctuation">(</span>aSurface<span class="token punctuation">)</span><span class="token punctuation">;</span>
            gp_Pnt aPnt <span class="token operator">=</span> aPlane<span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">Location</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            Standard_Real aZ   <span class="token operator">=</span> aPnt<span class="token punctuation">.</span><span class="token function">Z</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">if</span><span class="token punctuation">(</span>aZ <span class="token operator">&gt;</span> zMax<span class="token punctuation">)</span><span class="token punctuation">{</span>
                zMax <span class="token operator">=</span> aZ<span class="token punctuation">;</span>
                faceToRemove <span class="token operator">=</span> aFace<span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
    TopTools_ListOfShape facesToRemove<span class="token punctuation">;</span>
    facesToRemove<span class="token punctuation">.</span><span class="token function">Append</span><span class="token punctuation">(</span>faceToRemove<span class="token punctuation">)</span><span class="token punctuation">;</span>
    BRepOffsetAPI_MakeThickSolid BodyMaker<span class="token punctuation">;</span>
    BodyMaker<span class="token punctuation">.</span><span class="token function">MakeThickSolidByJoin</span><span class="token punctuation">(</span>myBody<span class="token punctuation">,</span> facesToRemove<span class="token punctuation">,</span> <span class="token operator">-</span>myThickness <span class="token operator">/</span> <span class="token number">50</span><span class="token punctuation">,</span> <span class="token number">1.e-3</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    myBody <span class="token operator">=</span> BodyMaker<span class="token punctuation">.</span><span class="token function">Shape</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre> 
  <h1><a id="_185"></a>三、构建螺纹</h1> 
  <h2><a id="_186"></a>创建表面</h2> 
  <p>到目前为止，已经学习了如何从3D曲线创建边缘。现在将学习如何创建一个二维曲线和曲面的边缘。为学习这方面的，在圆柱表面创建螺旋形轮廓。这个理论比前面的步骤更复杂，但是应用起来非常简单。第一步，计算这些圆柱面。现在已经熟悉了Geom包的曲线。要创建一个圆柱面(Geom_CylindricalSurface)，需要使用：</p> 
  <ul> 
   <li>一个坐标系统</li> 
   <li>一个半径</li> 
  </ul> 
  <p>使用相同的坐标系统neckAx2用于定位颈部，创建两个具有以下半径的圆柱形表面Geom_CylindricalSurface：<br> <img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512153442225.png" alt="在这里插入图片描述"></p> 
  <pre><code class="prism language-cpp">    <span class="token comment">// 螺纹：创建表面</span>
    <span class="token function">Handle</span><span class="token punctuation">(</span>Geom_CylindricalSurface<span class="token punctuation">)</span> aCyl1 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token function">Geom_CylindricalSurface</span><span class="token punctuation">(</span>neckAx2<span class="token punctuation">,</span> myNeckRadius <span class="token operator">*</span> <span class="token number">0.99</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token function">Handle</span><span class="token punctuation">(</span>Geom_CylindricalSurface<span class="token punctuation">)</span> aCyl2 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token function">Geom_CylindricalSurface</span><span class="token punctuation">(</span>neckAx2<span class="token punctuation">,</span> myNeckRadius <span class="token operator">*</span> <span class="token number">1.05</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre> 
  <h2><a id="_200"></a>定义二维曲线</h2> 
  <p>要创建瓶口，需要基于圆柱面制作一个实心圆柱体。通过表面上创建2D曲线来创建螺纹的轮廓。Geom包中定义的所有几何图形都是参数化的。这意味着Geom中的每条曲线或曲面都是用参数方程计算的。用以下参数方程定义Geom_CylindricalSurface：<br> P(U, V) = O + R * (cos(U) * xDir + sin(U) * yDir) + V * zDir，其中：</p> 
  <ul> 
   <li>P是由参数(U, V)定义的点</li> 
   <li>O、xDir、yDir、zDir分别是柱面局部坐标系的原点、X方向、Y方向和Z方向</li> 
   <li>R是圆柱表面的半径</li> 
   <li>U的取值范围是[0,2π]，且V是无穷大的</li> 
  </ul> 
  <p><img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512154229589.png" alt="在这里插入图片描述"><br> 有这样参数化几何的好处是，可以计算任何(U, V)的表面参数：</p> 
  <ul> 
   <li>三维点</li> 
   <li>该点1,2到N阶的导数向量<br> 这些参数方程的另一个好处是，可以把一个曲面看作是一个二维参数空间，它由(U, V)坐标系定义。例如，考虑颈部表面的参数范围：<br> <img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512155114188.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2plbGF0aW5l,size_16,color_FFFFFF,t_70" alt="在这里插入图片描述"></li> 
  </ul> 
  <p>假设在这个参数(U, V)空间上创建一条2D线，并计算它的3D参数曲线。根据行定义，结果如下：</p> 
  <table> 
   <thead> 
    <tr> 
     <th>情况</th> 
     <th>参数方程</th> 
     <th>参数曲线</th> 
    </tr> 
   </thead> 
   <tbody> 
    <tr> 
     <td>U = 0</td> 
     <td>P(V) = O + V * zDir</td> 
     <td>平行于Z方向的直线</td> 
    </tr> 
    <tr> 
     <td>V = 0</td> 
     <td>P(U) = O + R * (cos(U) * xDir + sin(U) * yDir)</td> 
     <td>平行于(O, X, Y)平面的圆</td> 
    </tr> 
    <tr> 
     <td>U != 0</td> 
     <td>V != 0 P(U, V) = O + R * (cos(U) * xDir + sin(U) * yDir) + V * zDir</td> 
     <td>描述圆柱高度和角度变化的螺旋曲线</td> 
    </tr> 
   </tbody> 
  </table>
  <pre><code class="prism language-cpp">    <span class="token comment">// 螺纹：创建边和线</span>
    TopoDS_Edge anEdge1OnSurf1 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeEdge</span><span class="token punctuation">(</span>anArc1<span class="token punctuation">,</span> aCyl1<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Edge anEdge2OnSurf1 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeEdge</span><span class="token punctuation">(</span>aSegment<span class="token punctuation">,</span> aCyl1<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Edge anEdge1OnSurf2 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeEdge</span><span class="token punctuation">(</span>anArc2<span class="token punctuation">,</span> aCyl2<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Edge anEdge2OnSurf2 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeEdge</span><span class="token punctuation">(</span>aSegment<span class="token punctuation">,</span> aCyl2<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Wire threadingWire1 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeWire</span><span class="token punctuation">(</span>anEdge1OnSurf1<span class="token punctuation">,</span> anEdge2OnSurf1<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Wire threadingWire2 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeWire</span><span class="token punctuation">(</span>anEdge1OnSurf2<span class="token punctuation">,</span> anEdge2OnSurf2<span class="token punctuation">)</span><span class="token punctuation">;</span>
    BRepLib<span class="token operator">::</span><span class="token function">BuildCurves3d</span><span class="token punctuation">(</span>threadingWire1<span class="token punctuation">)</span><span class="token punctuation">;</span>
    BRepLib<span class="token operator">::</span><span class="token function">BuildCurves3d</span><span class="token punctuation">(</span>threadingWire2<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre> 
  <h2><a id="_236"></a>创建边和线</h2> 
  <p>创建瓶子的基础轮廓，需要：</p> 
  <ul> 
   <li>计算颈部螺纹的边缘</li> 
   <li>从这些边中计算出两条线</li> 
  </ul> 
  <p><img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512155809529.png" alt="在这里插入图片描述"></p> 
  <pre><code class="prism language-cpp">    <span class="token comment">// 螺纹：创建边和线</span>
    TopoDS_Edge anEdge1OnSurf1 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeEdge</span><span class="token punctuation">(</span>anArc1<span class="token punctuation">,</span> aCyl1<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Edge anEdge2OnSurf1 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeEdge</span><span class="token punctuation">(</span>aSegment<span class="token punctuation">,</span> aCyl1<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Edge anEdge1OnSurf2 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeEdge</span><span class="token punctuation">(</span>anArc2<span class="token punctuation">,</span> aCyl2<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Edge anEdge2OnSurf2 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeEdge</span><span class="token punctuation">(</span>aSegment<span class="token punctuation">,</span> aCyl2<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Wire threadingWire1 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeWire</span><span class="token punctuation">(</span>anEdge1OnSurf1<span class="token punctuation">,</span> anEdge2OnSurf1<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Wire threadingWire2 <span class="token operator">=</span> <span class="token function">BRepBuilderAPI_MakeWire</span><span class="token punctuation">(</span>anEdge1OnSurf2<span class="token punctuation">,</span> anEdge2OnSurf2<span class="token punctuation">)</span><span class="token punctuation">;</span>
    BRepLib<span class="token operator">::</span><span class="token function">BuildCurves3d</span><span class="token punctuation">(</span>threadingWire1<span class="token punctuation">)</span><span class="token punctuation">;</span>
    BRepLib<span class="token operator">::</span><span class="token function">BuildCurves3d</span><span class="token punctuation">(</span>threadingWire2<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre> 
  <h2><a id="_256"></a>构建螺纹</h2> 
  <p>螺纹将是一个实体形状，所以现在必须计算这些线的面，这些面允许您连接这些线，这些面的外壳，然后是实体本身。这可能是一个漫长的操作。在定义基本拓扑时，总是有更快的方法来构建实体。现在可以通过用两条线创造一个实体，OpenCASCADE提供了一种快速的方法来实现这一点，通过建立loft：一个外壳或固体在给定的序列中穿越一组线。loft函数是在BRepOffsetAPI_ThruSections类中实现的，使用方法如下：</p> 
  <ul> 
   <li>通过创建类的实例初始化算法。如果要创建实体，必须指定此构造函数的第一个参数。默认情况下，BRepOffsetAPI_ThruSections构建一个外壳</li> 
   <li>使用AddWire方法添加连续的连接</li> 
   <li>使用CheckCompatibility方法激活检查是否有相同数量的边的选项。在本例中，线里各有两条边，因此可以禁用此选项</li> 
   <li>用Shape方法求出loft形状</li> 
  </ul> 
  <pre><code class="prism language-cpp">    <span class="token comment">// 构建螺纹</span>
    BRepOffsetAPI_ThruSections <span class="token function">aTool</span><span class="token punctuation">(</span>Standard_True<span class="token punctuation">)</span><span class="token punctuation">;</span>
    aTool<span class="token punctuation">.</span><span class="token function">AddWire</span><span class="token punctuation">(</span>threadingWire1<span class="token punctuation">)</span><span class="token punctuation">;</span>
    aTool<span class="token punctuation">.</span><span class="token function">AddWire</span><span class="token punctuation">(</span>threadingWire2<span class="token punctuation">)</span><span class="token punctuation">;</span>
    aTool<span class="token punctuation">.</span><span class="token function">CheckCompatibility</span><span class="token punctuation">(</span>Standard_False<span class="token punctuation">)</span><span class="token punctuation">;</span>
    TopoDS_Shape myThreading <span class="token operator">=</span> aTool<span class="token punctuation">.</span><span class="token function">Shape</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre> 
  <h1><a id="_272"></a>四、整合模型</h1> 
  <p>现在将要完成了瓶子的制作。使用TopoDS_Compound 和 BRep_Builder 类从 myBody和myThreading构建单个形状：</p> 
  <pre><code class="prism language-cpp">    <span class="token comment">// 整合模型</span>
    TopoDS_Compound aRes<span class="token punctuation">;</span>
    BRep_Builder aBuilder<span class="token punctuation">;</span>
    aBuilder<span class="token punctuation">.</span>MakeCompound <span class="token punctuation">(</span>aRes<span class="token punctuation">)</span><span class="token punctuation">;</span>
    aBuilder<span class="token punctuation">.</span>Add <span class="token punctuation">(</span>aRes<span class="token punctuation">,</span> myBody<span class="token punctuation">)</span><span class="token punctuation">;</span>
    aBuilder<span class="token punctuation">.</span>Add <span class="token punctuation">(</span>aRes<span class="token punctuation">,</span> myThreading<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">return</span> aRes<span class="token punctuation">;</span>
</code></pre> 
  <h2><a id="_285"></a>五、实际效果</h2> 
  <p>创建一个头文件，添加以下函数，并将瓶子构建内容加入到函数中：</p> 
  <pre><code class="prism language-cpp">TopoDS_Shape <span class="token function">MakeBottle</span><span class="token punctuation">(</span><span class="token keyword">const</span> Standard_Real myWidth<span class="token punctuation">,</span> 
                        <span class="token keyword">const</span> Standard_Real myHeight<span class="token punctuation">,</span>
                        <span class="token keyword">const</span> Standard_Real myThickness<span class="token punctuation">)</span>
                        <span class="token punctuation">{</span>
                        <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>
                        <span class="token punctuation">}</span>
</code></pre> 
  <p>编写三维显示界面，实现显示瓶子：</p> 
  <pre><code class="prism language-cpp">    <span class="token comment">// 创建一个立方体作测试</span>
    TopoDS_Shape t_topo_bottle <span class="token operator">=</span> <span class="token function">MakeBottle</span><span class="token punctuation">(</span><span class="token number">70.0</span><span class="token punctuation">,</span> <span class="token number">50.0</span><span class="token punctuation">,</span> <span class="token number">30.0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token function">Handle</span><span class="token punctuation">(</span>AIS_Shape<span class="token punctuation">)</span> t_ais_bottle <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token function">AIS_Shape</span><span class="token punctuation">(</span>t_topo_bottle<span class="token punctuation">)</span><span class="token punctuation">;</span>
    m_context<span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">Display</span><span class="token punctuation">(</span>t_ais_bottle<span class="token punctuation">,</span> Standard_True<span class="token punctuation">)</span><span class="token punctuation">;</span>
    m_view<span class="token operator">-</span><span class="token operator">&gt;</span><span class="token function">FitAll</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre> 
  <p>显示效果：<br> <img src="https://uzshare.com/_p?https://img-blog.csdnimg.cn/20190512162645298.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2plbGF0aW5l,size_16,color_FFFFFF,t_70" alt="在这里插入图片描述"></p> 
  <h1><a id="_309"></a>项目仓库</h1> 
  <p><a href="https://github.com/Jelatine/JellyCAD" rel="nofollow">https://github.com/Jelatine/JellyCAD</a></p> 
 </div> 
 <link href="https://csdnimg.cn/release/phoenix/mdeditor/markdown_views-258a4616f7.css" rel="stylesheet"> 
</div>
  </article>
  
  




</div>

        </div>
        <div class="col-second">
          <div class="col-box col-box-author">
  <img class="avatar" src="https://uzstatic-360cdn.belost.xyz/theme/default/images/logo.png" alt="柚子社区">
  <div class="col-box-title name">NotBeCN</div>
  <!-- <p>最新资讯</p> -->
  <p class="contact">
    
    <a href="mailto:fandyvon@163.com" target="_blank">邮箱</a>
    
    <a href="https://uzshare.com" target="_blank">柚子社区</a>
    
    <a href="https://uzzz.org" target="_blank">找组织</a>
    
  </p>
</div>

<div class="col-box">
  <div class="col-box-title">最新</div>
  <ul class="post-list">
    
      <li><a class="post-link" href="/2019/05/14/zxh1220_90138586.html">[原创软件] [软件发布] 定时备份文件发送邮箱，不再怕数据丢失了</a></li>
    
      <li><a class="post-link" href="/2019/05/14/weixin_45037290_90140056.html">Get智能写作满月记 ——产品篇</a></li>
    
      <li><a class="post-link" href="/2019/05/14/nulio__90138386.html">《深度探索C++对象模型》..............</a></li>
    
      <li><a class="post-link" href="/2019/05/13/qq_41248707_90140031.html">mysql 多表联查之连接查询</a></li>
    
      <li><a class="post-link" href="/2019/05/13/qq_21122683_90125902.html">golang基础(二)</a></li>
    
      <li><a class="post-link" href="/2019/05/13/1557726108256.html">今日份的PTA刷题</a></li>
    
      <li><a class="post-link" href="/2019/05/12/zzzfffei_90137366.html">Android之折线图</a></li>
    
      <li><a class="post-link" href="/2019/05/12/zzzfffei_90136638.html">Android之实现选中时改变样式</a></li>
    
  </ul>
</div>

<div class="col-box post-toc hide">
  <div class="col-box-title">目录</div>
</div>

<div class="col-box">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- right_sidebar -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8889449066804352"
       data-ad-slot="2081363239"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>


        </div>
      </div>
    </div>

    <footer class="footer">
<div class="wrapper">
&copy; 2019 
</div>
</footer>

<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$']]}});</script>
<script src="/js/easybook.js"></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-123344652-5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-123344652-5');
</script>


<script data-ad-client="ca-pub-8889449066804352" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.async = true;
  hm.src = "https://hm.baidu.com/hm.js?9b378145d7399199b371d067f4c8be96";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>




  </body>

</html>
