<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>程序实现曲面切割 « NotBeCN</title>
  <meta name="description" content="                      下面这段代码来自一个客户，实现用一个曲面切割另外一个，比如用一块铁板把一个两头有盖的汽油桶切成两个开口的桶。原理很简单，就是利用了AcDbSurface的SliceBySurface方法：     &nbsp;     切割前：          &nbsp;     ...">

  <link rel="stylesheet" href="/css/main.css">
  <link rel="canonical" href="https://notbe.cn/2017/08/01/weixin_34327761_90125714.html">
  <link rel="alternate" type="application/rss+xml" title="NotBeCN" href="https://notbe.cn/feed.xml" />
</head>


  <body>

    <div class="header-placeholder"></div>
<header class="header">
  <div class="wrapper">
    <div id="sidebar-toggle">TOC</div>
    <a class="site-title" href="/">NotBeCN</a>
    <nav class="site-nav">
      
        
        <a class="page-link" href="/about/" target="_blank">关于</a>
      
        
        <a class="page-link" href="https://uzshare.com" target="_blank">社区</a>
      
        
        <a class="page-link" href="/donate/" target="_blank">Donate</a>
      
        
        <a class="page-link" href="/games/shejiyazi/" target="_blank">射个鸭子</a>
      
    </nav>
  </div>
</header>


    <div class="page-content">
      <div class="wrapper">
        <div class="col-main">
          <div class="post">

  <header class="post-header">
    <h1 class="post-title">程序实现曲面切割</h1>
    <p class="post-meta">Aug 1, 2017</p>
  </header>

  <article class="post-content">
    <div id="article_content" class="article_content clearfix csdn-tracking-statistics" data-pid="blog" data-mod="popu_307" data-dsm="post"> 
 <link rel="stylesheet" href="https://csdnimg.cn/release/phoenix/template/css/ck_htmledit_views-f57960eb32.css"> 
 <link rel="stylesheet" href="https://csdnimg.cn/release/phoenix/template/css/ck_htmledit_views-f57960eb32.css"> 
 <div class="htmledit_views" id="content_views"> 
  <div class="content-detail markdown-body"> 
   <h1 style="font-size:14.7px;color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;"><br></h1> 
   <div class="blogpost-body" style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;"> 
    <p style="line-height:1.5;">下面这段代码来自一个客户，实现用一个曲面切割另外一个，比如用一块铁板把一个两头有盖的汽油桶切成两个开口的桶。原理很简单，就是利用了AcDbSurface的SliceBySurface方法：</p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;">切割前：</p> 
    <p style="line-height:1.5;"><a href="https://images0.cnblogs.com/blog/30437/201306/03181923-80c2313854e84646850d3c7c8c986183.png" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><img title="image" alt="image" src="https://images0.cnblogs.com/blog/30437/201306/03181926-8bd28b5e2fc1455493f7f05df189072d.png" width="244" height="216" style="border:0px;background-image:none;"></a></p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;">切割后，为了看得清楚，把无盖桶移动了一下：</p> 
    <p style="line-height:1.5;"><a href="https://images0.cnblogs.com/blog/30437/201306/03181929-4654827f32814928ba197e60e7497c8f.png" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;"><img title="image" alt="image" src="https://images0.cnblogs.com/blog/30437/201306/03181930-5dabc328c0a24c1992c252f852c069c3.png" width="244" height="204" style="border:0px;background-image:none;"></a></p> 
    <p style="line-height:1.5;">&nbsp;</p> 
    <p style="line-height:1.5;">代码：</p> 
    <p style="line-height:1.5;"></p> 
    <pre><code class="language-csharp">        [CommandMethod(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"TestSliceSurface"</span>)]
        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">public</span> <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">void</span> TestSliceSurface()
        {
            Document doc = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument;
            var ed = doc.Editor;

            <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> (DocumentLock docLock = doc.LockDocument())
            {
                Database db = doc.Database;
                <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">using</span> (Transaction ts = db.TransactionManager.StartTransaction())
                {
                    BlockTableRecord btr = ts.GetObject(db.CurrentSpaceId, OpenMode.ForWrite) <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">as</span> BlockTableRecord;
                    var peo1 = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> PromptEntityOptions(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"\nSelect first surface"</span>);
                    peo1.SetRejectMessage(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"\nMust be a surface."</span>);
                    peo1.AddAllowedClass(<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">typeof</span>(AcDb.Surface), <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">false</span>);

                    var per1 = ed.GetEntity(peo1);
                    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (per1.Status != PromptStatus.OK)
                        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">return</span>;

                    var obj1 = ts.GetObject(per1.ObjectId, OpenMode.ForWrite);
                    var surf1 = obj1 <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">as</span> AcDb.Surface;
                    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (surf1 == <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">null</span>)
                    {

                        ed.WriteMessage(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"\nFirst object must be a surface."</span>);
                        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">return</span>;
                    }
                    
                    var peo2 = <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">new</span> PromptEntityOptions(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"\nSelect second surface"</span>);
                    peo2.SetRejectMessage(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"\nMust be a surface."</span>);
                    peo2.AddAllowedClass(<span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">typeof</span>(AcDb.Surface), <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">false</span>);

                    var per2 = ed.GetEntity(peo2);
                    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (per2.Status != PromptStatus.OK)
                        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">return</span>;

                    var obj2 = ts.GetObject(per2.ObjectId, OpenMode.ForWrite);
                    var surf2 = obj2 <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">as</span> AcDb.Surface;
                    <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">if</span> (surf2 == <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">null</span>)
                    {

                        ed.WriteMessage(<span class="str" style="line-height:1.5;color:rgb(0,96,128);">"\nSecond object must be a surface."</span>);
                        <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">return</span>;
                    }

                    SurfaceSliceResults ss = surf1.SliceBySurface(surf2);

                    btr.AppendEntity(ss.NegativeHalfSurface);
                    ts.AddNewlyCreatedDBObject(ss.NegativeHalfSurface, <span class="kwrd" style="line-height:1.5;color:rgb(0,0,255);">true</span>);

                    ts.Commit();
                    ts.Dispose();

                }
                docLock.Dispose();
                
            }
            
        }</code></pre> 
    <p style="line-height:1.5;"></p> 
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    作者：
    <a href="http://junqilian.cnblogs.com/" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;">峻祁连</a>
    <br> 邮箱：junqilian@163.com&nbsp;
    <br> 出处：
    <a href="http://junqilian.cnblogs.com/" rel="nofollow" style="color:rgb(26,139,200);text-decoration:none;">http://junqilian.cnblogs.com</a>&nbsp;
    <br> 转载请保留此信息。
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    <br>
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    <br>
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    <br>
   </div> 
   <div style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;font-size:13.3333px;">
    <br>
   </div> 
   <div> 
    <font color="#4b4b4b">本文转自峻祁连. Moving to Cloud/Mobile博客园博客，原文链接：http://www.cnblogs.com/junqilian/archive/2013/06/03/3115932.html</font>
    <span style="color:rgb(75,75,75);font-family:Verdana, Geneva, Arial, Helvetica, sans-serif;">，如需转载请自行联系原作者</span> 
   </div> 
  </div> 
 </div> 
</div>
  </article>
  
  




</div>

        </div>
        <div class="col-second">
          <div class="col-box col-box-author">
  <img class="avatar" src="https://uzstatic-360cdn.belost.xyz/theme/default/images/logo.png" alt="柚子社区">
  <div class="col-box-title name">NotBeCN</div>
  <!-- <p>最新资讯</p> -->
  <p class="contact">
    
    <a href="mailto:fandyvon@163.com" target="_blank">邮箱</a>
    
    <a href="https://uzshare.com" target="_blank">柚子社区</a>
    
    <a href="https://uzzz.org" target="_blank">找组织</a>
    
  </p>
</div>

<div class="col-box">
  <div class="col-box-title">最新</div>
  <ul class="post-list">
    
      <li><a class="post-link" href="/2019/05/14/zxh1220_90138586.html">[原创软件] [软件发布] 定时备份文件发送邮箱，不再怕数据丢失了</a></li>
    
      <li><a class="post-link" href="/2019/05/14/weixin_45037290_90140056.html">Get智能写作满月记 ——产品篇</a></li>
    
      <li><a class="post-link" href="/2019/05/14/nulio__90138386.html">《深度探索C++对象模型》..............</a></li>
    
      <li><a class="post-link" href="/2019/05/13/qq_41248707_90140031.html">mysql 多表联查之连接查询</a></li>
    
      <li><a class="post-link" href="/2019/05/13/qq_21122683_90125902.html">golang基础(二)</a></li>
    
      <li><a class="post-link" href="/2019/05/13/1557726108256.html">今日份的PTA刷题</a></li>
    
      <li><a class="post-link" href="/2019/05/12/zzzfffei_90137366.html">Android之折线图</a></li>
    
      <li><a class="post-link" href="/2019/05/12/zzzfffei_90136638.html">Android之实现选中时改变样式</a></li>
    
  </ul>
</div>

<div class="col-box post-toc hide">
  <div class="col-box-title">目录</div>
</div>

<div class="col-box">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- right_sidebar -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8889449066804352"
       data-ad-slot="2081363239"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>


        </div>
      </div>
    </div>

    <footer class="footer">
<div class="wrapper">
&copy; 2019 
</div>
</footer>

<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$']]}});</script>
<script src="/js/easybook.js"></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-123344652-5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-123344652-5');
</script>


<script data-ad-client="ca-pub-8889449066804352" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.async = true;
  hm.src = "https://hm.baidu.com/hm.js?9b378145d7399199b371d067f4c8be96";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>




  </body>

</html>
